Table users {
    id uuid [primary key]
    name varchar
    surname varchar
    last_name varchar
    login varchar [not null, unique]
    password varchar [not null, note: 'hash' ]
    registered_at timestamp
    photo_id uuid
    failed_attempts_count integer
    is_deleted boolean
}

Table revoked_tokens {
    id uuid [primary key]
    access_token varchar
    revoked_at datetime
}

Table images {
    id uuid [primary key]
    image_name varchar
    image_data longblob
}
Ref: users.photo_id > images.id

// Depricated. Instead JWT
// Table auth_sessions {
//     sid uuid [primary key]
//     expired timestamp
//     status varchar
//     user_id uuid
// } 
// Ref: auth_sessions.user_id > users.id
 
Table group_enter_requests {
    id uuid [primary key]
    user_id uuid
    group_id uuid
    is_approved boolean
    datetime datetime
}

Table group_participants {
    id uuid [primary key]
    user_id uuid
    group_id uuid
}

Table groups {
    id uuid [primary key]
    creator_id uuid
    name varchar
    description varchar
    is_open boolean
    max_participants_count integer
    is_deleted boolean
}

Ref: groups.creator_id > users.id
Ref: group_participants.user_id > users.id
Ref: group_participants.group_id > groups.id
Ref: group_enter_requests.user_id > users.id
Ref: group_enter_requests.group_id > groups.id

Table slot_participants {
    id uuid [primary key]
    user_id uuid
    slot_id uuid
    is_attended boolean
    is_paid boolean
    custom json
}

Table slots {
    id uuid [primary key]
    creator_id uuid
    repeat_id uuid
    name varchar
    description varchar
    is_open boolean
    datetime datetime
    duration integer
    max_participants_count integer
}  

Table rapids {
    id uuid [primary key]
    weekdays array [null]
    start_date timestamp
    end_date timestamp
    datetime datetime
    duration integer
    months array [null]
}

Ref: slot_participants.user_id > users.id
Ref: slot_participants.slot_id > slots.id
Ref: slots.creator_id > users.id 
Ref: slots.repeat_id > rapids.id

Table events { //составной ключ??
    id uuid [primary key]
    template_id uuid
    datetime datetime
}
Ref: events.template_id > events_template.id

Table events_template {
    id uuid [primary key]
    repeat_id uuid
    group_id uuid
    name varchar
    description varchar
    max_participants_count integer
}
Ref: events_template.repeat_id > rapids.id
Ref: events_template.group_id > groups.id


Table group_event_participants {
    id uuid [primary key]
    event_id uuid
    participant_id uuid
    is_attended boolean
    is_paid boolean
    custom json
}
Ref: group_event_participants.event_id > events.id
Ref: group_event_participants.participant_id > group_participants.id 